spring.application.name=smart-internship-tracker

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/smart_internship_tracker}
spring.datasource.username=${DATABASE_USERNAME:smart_tracker}
spring.datasource.password=${DATABASE_PASSWORD:smart_tracker}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

app.jwt.secret=${JWT_SECRET:01234567890123456789012345678901}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
